#!/usr/bin/env bash

args=("$@")


docs_build () {
    bundle exec jekyll build
}

docs_serve () {
    bundle exec jekyll serve
}

docs_deploy () {
    docs_build
    aws s3 sync --delete _site/ s3://yo-lang.net
    if [ "${args[1]}" != "-s3-only" ]
    then
        aws cloudfront create-invalidation --distribution-id 'EFR5XO3UYE8F7' --paths "/*"
    fi
}

docs() {
    cd ./docs
    case "${args[1]}" in
        "build") docs_build ;;
        "serve") docs_serve ;;
        "deploy") docs_deploy ;;
        *) echo "F"; exit 1 ;;
    esac
}


vscode() {
    code --extensionDevelopmentPath="`pwd`/tools/yo-lang-vscode/" .
}


case "${args[0]}" in
    "docs") docs ;;
    "vscode") vscode ;;
    *) echo "F"; exit 1 ;;
esac
